### ISSUE TITLE
Empty EDN causes misleading exception

### ISSUE THREAD

**Issue by chachi** [tolitius/cprop#12]
When my `conf` file was completely empty (no `{}` even), I got the very perplexing error:
`Caused by: java.lang.RuntimeException: could not find a configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property`

I believe this is because the deep merging fails when either the resource or default file is empty.

Not allowing an empty EDN file seems fine to me, but perhaps a specific error message is warranted for this case.

**Comment by tolitius** [comment]
thanks for bringing it up.

I pushed a "clarification fix". It is in `0.1.10-SNAPSHOT`.

It now notifies whenever the config is empty (`{}`/`[]`/..., `""` or `nil`) as well as would throw at the end of the merge in case it is not able to find config content in anywhere:

```clojure
=> (load-config)
(!) read config from resource: "config.edn", but it is empty
(!) read config from file: "dev-resources/config.edn", but it is empty

java.lang.RuntimeException: could not find a non empty configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property
```

try `0.1.10-SNAPSHOT`, let me know if that clears it up.

**Comment by chachi** [comment]
That looks great, thanks for the fast fix!
