### ISSUE TITLE
Add CLI as a source of configuration data

### ISSUE THREAD

**Issue by crimeminister** [tolitius/cprop#19]
It is useful to be able to supply and/or override configuration information from the command line. This [small gist](https://gist.github.com/crimeminister/e9ac993cb9d0ba65f6a113351421b4cc) is the snippet I use to merge options taken from CLI into configuration loaded by cprop. It interprets CLI options containing double hyphens as indicating nesting, analogous to how cprop treats environment variables. I would like to see a `(from-cli)` source added, and will submit a PR if that helps.

**Comment by tolitius** [comment]
yea, that's a great idea

I have a question and a concern:

## question

I usually pass things from command line via `-Dprop__ert_y`, is it not good enough?

## concern

does it add a dependency to `cprop`?
currently `cprop` has no deps, and I'd like to keep it that way

**Comment by crimeminister** [comment]
My projects are already using what's offered by `clojure/tools.cli`; using two mechanisms to supply information on the CLI might get a bit unwieldy. That said, I wouldn't want to add `clojure/tools.cli` (or any other library) as a dependency either. I imagine a `(from-cli)` source function accepting a map of options, however generated, to make it usable with other libraries; it seems most CLI parsing libraries return results as a map.

**Comment by tolitius** [comment]
yea, it there is no dep needed it's a great feature to have

**Comment by crimeminister** [comment]
This one is pretty long in the tooth, closing!
