### ISSUE TITLE
Feature Request: EDN to Properties class

### ISSUE THREAD

**Issue by evmin** [tolitius/cprop#21]
As a developer who embeds Java frameworks into Clojure enclosure (pun intended) I would like to be able to convert EDN into java.util.Properties in memory.

So in addition to the existing route via file:
```clojure
(t/map->props-file config)
"/tmp/cprops-1475854845508-538388633502378948.tmp"
```
I would appreciate having a separate function to get the Object:
```clojure
(t/map->props config)
```

**Comment by tolitius** [comment]
which "`Object`" and _why_?

In the latest snapshot (`0.1.11-SNAPSHOT`) you can get the actual String without creating a file by passing optional parameters:

```clojure
=> (require '[cprop.tools :as t])

=> (t/map->props-file {:a 42 :b {:c 34} :d 28})
"/var/folders/4f/36_45md562bcg1ym0hjjr9hr0000gp/T/cprops-1501512818460-2420638496498138229.tmp"

=> (t/map->props-file {:a 42 :b {:c 34} :d 28} {:create? false})
"d=28\nb.c=34\na=42\n"
```

you can also pass a custom file path:

```clojure
=> (t/map->props-file {:a 42 :b {:c 34} :d 28} {:path "/tmp/foo.bar"})
"/tmp/foo.bar"
```

same applies to `map->env-file`:

```clojure
=> (t/map->env-file {:a 42 :b {:c 34} :d 28} {:create? false})
"export D=28\nexport B__C=34\nexport A=42\n"
```

**Comment by evmin** [comment]
The main imperative is to skip the loop of generating the file first and and then re-importing it back into java.util.Properties all together. In a situation when a Java framework is used from within the Clojure this could be counter productive.

My use case - Apache Camel, which requires java.util.Properties as the value source for PropertyComponent to be set within Camel context. I am specifically looking for setOverride Properties method:
https://camel.apache.org/maven/camel-2.15.0/camel-core/apidocs/org/apache/camel/component/properties/PropertiesComponent.html

Object wise - java.util.Properties would be the best, HashMap great.

What would probably work as well, and with minimal effort, if the function cprop.tools/map->props have been made public:

```clojure
(defn- map->props [m]
  (map->flat m key->prop "."))
```
Thank you!

**Comment by tolitius** [comment]
makes sense. `map->props` won't really give you `Properties`, but rather a seq of entities:
```clojure
=> (#'cprop.tools/map->props {:a 42 :b {:c 34 :d {:e 28}} :f 13})
(["f" 13] ["b.d.e" 28] ["b.c" 34] ["a" 42])
```

In the latest snapshot (`0.1.11-SNAPSHOT`) I added `map->properties` that will do what you need without creating a temp file:

```clojure
=> (require '[cprop.tools :as t])

=> (t/map->properties {:a 42 :b {:c 34 :d {:e 28}} :f 13})
{"a" "42", "b.c" "34", "b.d.e" "28", "f" "13"}

=> (type (t/map->properties {:a 42 :b {:c 34 :d {:e 28}} :f 13}))
java.util.Properties
```

Interestingly enough `map->props-file` came to existence for a Java library that _required_ an actual `.properties` file.

**Comment by evmin** [comment]
Brilliant, thank you.

Interestingly enough, cprops was one of the enabling tools that made moving from Springboot to Clojure a breeze. Really appreciate your efforts here.

**Comment by tolitius** [comment]
glad to hear that, thanks for the feedback

**Comment by tolitius** [comment]
released `0.1.11` with `map->properties` in case you need this feature and can't release with snapshots.

**Comment by evmin** [comment]
Wow, that was quick. Thank you. 

Question, do I understand correctly that map->properties is still going through the file generation route? In containerised environment that would create a layer per actual container. 

Would it also be possible to make the map->props function public?
I do not see any harm in this?

**Comment by tolitius** [comment]
`map->properties` does not create a temp file, it passes a `{:create false}` when calling `map->props-file`: https://github.com/tolitius/cprop/blob/master/src/cprop/tools.cljc#L75 which bypasses I/O all together.

The reason I don't want to open up `map->props` is because it is an internal / intermediate step that is useful for other public APIs. Once it is open, it is a guarantee going forward, which limits the agility of future changes.

**Comment by evmin** [comment]
Makes sense, thank you. This is awesome.

**Comment by evmin** [comment]
Not sure what is going wrong, here is the code:

```clojure
(def config (load-config :resource "config.edn"
                         :merge [(from-system-props)
                                 (from-env)]))

(defn config-properties []
        (t/map->properties config))
```

Results in:
```
Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding., compiling:(/private/var/folders/hl/dz69nmk50kl_cn4fgd904dwh0000gn/T/form-init5308382940781279132.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.util.Properties.loadConvert(Properties.java:574)
	at java.util.Properties.load0(Properties.java:391)
	at java.util.Properties.load(Properties.java:317)
	at cprop.tools$map__GT_properties.invokeStatic(tools.cljc:76)
	at cprop.tools$map__GT_properties.invoke(tools.cljc:71)

```

If "(from-env)" is removed, everything works. I suspect it is one of the env variables that is causing this. I'm on Mac. 

Should I file it as a separate issue?
