### ISSUE TITLE
Support for ~ shorthand in load-config :file

### ISSUE THREAD

**Issue by sooheon** [tolitius/cprop#23]
For example:

```clojure
(is (= (load-config :file (str (System/getenv "HOME") "/.secrets.edn"))
       (load-config :file "~/.secrets.edn")))
```

[aero](https://github.com/juxt/aero) supports this, but I prefer cprop's cursors over aero's reader tags.

**Comment by tolitius** [comment]
makes sense. check out `0.1.12-SNAPSHOT`, it's there.

**Comment by sooheon** [comment]
Wow that was quick. Thanks!
