### ISSUE TITLE
:env key?

### ISSUE THREAD

**Issue by leblowl** [tolitius/cprop#25]
With Leiningen, I was able to embed variables into my `project.clj` by using a top-level project.clj `:env` key with a map of variables as it's value. I believe the same key works in profiles. But I couldn't find this documented anywhere except in `environ` docs: https://github.com/weavejester/environ. Is this a Leiningen core functionality? Should we add this to the README for `cprop`?

**Comment by leblowl** [comment]
For Leiningen, I also found it useful to add `project.clj`-defined variables as constants in my `config` namespace, like this: 
```
(def ^:const css-version
  "Version string for our app's main CSS file."
  (:css-version (load-config)))
```
because the Leiningen variables are not available at run-time for a JAR. Another solution is to read the variable from a separate file, but then more logic is necessary to gather that variable and use it from within Leiningen tasks and such. I think it might be simpler to define some constants within the project.clj itself. Or use `boot`, which I think facilitates easier Clojure coding in your build file. But for the Leiningen folks like I, I was confused why my variables were not showing up at run-time. If you think this info is helpful, I can add some documentation for it.

**Comment by tolitius** [comment]
> _Should we add this to the README for cprop?_

is it `cprop` related? could you give an example (maybe a little sample project) where you use ENV variables with lein? Usually it is done via plugins or built ins (i.e. env `LEIN_PASSWORD` would sub `:password :env`).

(`environ` specifically parses lein configs. For environment variables it looks at `.lein-env` to get ENVs)

**Comment by leblowl** [comment]
For me, knowing how to embed cprop accessible variables in my Leiningen config would have been helpful. So I think that is cprop related. The question is: How can I define project level constants for cprop from my project.clj file or profiles.clj file? Environ has that use-case right on the front-page: 
```
{:dev  {:env {:database-url "jdbc:postgresql://localhost/dev"}}
 :test {:env {:database-url "jdbc:postgresql://localhost/test"}}}
```
Cprop says it handles profiles at the top of the Github page, but I don't see any docs. The `:env` key works, but it isn't documented in `cprop` docs...

**Comment by leblowl** [comment]
I feel pretty silly. Environ was included by another library. I was so perplexed why that :env key even worked as I couldn't find that in the source for either cprop or Leiningen. So yea this isn't really related to cprop, however if any body wants to use cprop with environ, you can and it appears to work well. But I also see another reason to keep libraries as slim as possible in terms of their dependencies.

**Comment by tolitius** [comment]
> _specifically the profiles part, are we talking about a Leiningen profile here?_

not really. what I mean by profile is different configuration groups, it could be as standard as a common 4-tier architecture: `development`, `testing`, `staging`, `production`, but could also be anything else custom.

the term profile is used in the "config space" to specify these groups. [here](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html) is an example.

as to cprop, the point is not to have specific profile/env/etc. markers in configuration files but to be able to define a merge strategy / order / sources that would allow the app internal configuration to stay the same, and the overrides to be driven from elsewhere: system properties, ENV, consul, etcd, zookeeper, etc.

as to reading `lein`, or `boot` or `something else`. I think it is convenient, but I also think it adds complexity: i.e. now you have to remember that you have some ENV variables are in your bash profile, some in the terminal, some are set by the Docker file, and "oh yea, these? these might have come from profile.clj or .lein-env or .boot-env or ...".

I think ENV variables should be explicitly set i.e. `export FOO=42` and they belong in ENV/OS, not in `project.clj` or anything else specific to the language or tool.

**Comment by leblowl** [comment]
Ok, that makes sense. I tend to agree. So what do you think is a good pattern for a global/common profile? Use a `common.edn` configuration file? My only issue with that as a Leiningen user, is how can I access those variables from within my `project.clj` ? I want to access my global variables and use those values in other Leiningen tasks which are specified in the project.clj. In my case, I have this app-global CSS version, which will always remain the same regardless of the environment. I want to use that version in Leiningen tasks for SASSC and use it throughout my code while rendering HTML that references that CSS file. I realize this is sort of out-of-scope for `cprop`, but I think I would have to require cprop within my project.clj inside a tilde macro, if that even works...

**Comment by tolitius** [comment]
> _I want to access my global variables and use those values in other Leiningen tasks which are specified in the project.clj_

yea, this is a bit out of scope for cprop, and has to do with reading ENV variables by `lein`. I don't think you would need to `require cprop` within `project.clj` as it won't help you access ENV variables _within project.clj_.

sounds more of a `lein` question. in `boot` you can just `(System/getenv "ENV_VAR_NAME")`, but in `lein` I am not sure how to do it without plugins.

**Comment by leblowl** [comment]
Thanks!
