### ISSUE TITLE
Non-numeric values are parsed as numbers

### ISSUE THREAD

**Issue by luontola** [tolitius/cprop#27]
Given an environment variable with the value `7 Nov 22:44:53 2015`, then `cprop.source/read-system-env` accidentally parses it as the number `7` instead of keeping it as a string.

**Comment by tolitius** [comment]
ah... interesting. thanks for reporting it.

this is due the the non "EDN formatted thing":

```clojure
=> (require '[clojure.edn :as edn])

=> (edn/read-string "7 Nov 22:44:53 2015")
7
```
also:
```clojure
boot.user=> (edn/read-string "7Nov 22:44:53 2015")
java.lang.NumberFormatException: Invalid number: 7Nov
```

I was wondering for some time now whether to have an option param where it would treat/read/overwrite all ENV vars as strings for cases like this.

If you have other ideas, let's talk :)

**Comment by tolitius** [comment]
other things to consider is to:

* optionally take in custom regex and a function to parse it
* take in custom `*data-readers*`

**Comment by luontola** [comment]
I was able to work around this by changing the parameters to be formatted `2015-12-27T17:32:00Z`, which makes `edn/read-string` throw an exception but `cprop.source/str->value` has a `catch` for that, so the value is returned unmodified.

I suppose wrapping the value in double quotes (`"2015-12-27T17:32:00Z"`) would also work by making it valid EDN, but since my variables are in a YAML file, it'll need double double quotes: `SOME_YAML_VAR: "\"2015-12-27T17:32:00Z\""`

**Comment by luontola** [comment]
An option for disabling EDN parsing would be nice. I don't use that feature anyways.

**Comment by tolitius** [comment]
I added `:as-is?` optional param to source (sysprops, propfile and env related) functions which will read props as is (i.e. as strings):
```
$ export FOO='"4242"'
$ export BAR=4242
$ export DATE='7 Nov 22:44:53 2015'
$ export VEC='[1 2 3 4]'
```
```clojure
[cprop]$ boot dev
=> (require '[cprop.source :as s])

=> (:foo (s/from-env))
"4242"
=> (:bar (s/from-env))
4242
=> (:date (s/from-env))
7
=> (:vec (s/from-env))
[1 2 3 4]
```
but
```clojure
=> (:foo (s/from-env {:as-is? true}))
"\"4242\""
=> (:bar (s/from-env {:as-is? true}))
"4242"
=> (:date (s/from-env {:as-is? true}))
"7 Nov 22:44:53 2015"
=> (:vec (s/from-env {:as-is? true}))
"[1 2 3 4]"
```

it should be in `cprop-0.1.14-SNAPSHOT`. let me know if it works for you.

**Comment by tolitius** [comment]
also can be used at the top level: `(load-config ... :as-is? true)`

**Comment by luontola** [comment]
Thanks. `:as-is?` works well.

**Comment by tolitius** [comment]
great, thanks for the feedback. it is in `cprop-0.1.14` (release version).
