### ISSUE TITLE
Question marks in config values - from ENV -> cprop ? 

### ISSUE THREAD

**Issue by joefromct** [tolitius/cprop#32]
I've built an app that has my dev configuration with something like the following:

``` lisp
{ :web {:port 8080
       :basic-auth? false}}
```

Upon time-to-deploy I've learned I can't have an environment variable with a `?` in it...

I know I can "nest maps" with the double underscore trick (and that works great) but is there anyway to convey a config with a question mark from the ENV into my config?  

If not, it seems I should refactor my app so that any config variables with question marks aren't present? 

I was hoping to do something like this, but now i'm realizing i might have some config surgery to do:
``` sh
WEB__BASIC_AUTH\?=true java -jar my-uberjar.jar
```

Maybe i shouldn't have used question marks for "flag" type configuration values... 

any tips appreciated, thanks in advance.

**Comment by joefromct** [comment]
This is my work around for today i guess:

``` clojure
(defn- keyword-has-hyphen? [k]
  (if (= (-> k name last) \-)
    true))

(defn- assoc-with-new-name [k]
  (let [old-n (name k)
        new-n (clojure.string/replace old-n #"-$" "?")]
    [k (keyword new-n)]))

(defn- start-web [{:keys [web]}]
  {:pre [map? web]}
  ;; this is because shell variables can't have question marks :/
  ;; https://github.com/tolitius/cprop/issues/32
  (let [replace-?-in-web (->> web
                              keys
                              (filter keyword-has-hyphen?)
                              (mapcat assoc-with-new-name)
                              (apply hash-map)
                              (clojure.set/rename-keys web))]
    (run-jetty (compile-middleware #'app) replace-?-in-web)))
```

**Comment by tolitius** [comment]
the usual practice for variable names that are meant/subject to being overridden is **not** to use `?`s.

not only this makes life easier with ENV/system props overrides, but it also makes configs more _portable_: i.e. convert to JSON/other format and send/use by other applications, potentially in different languages.

> _Maybe i shouldn't have used question marks for "flag" type configuration values..._

yep :)
