### ISSUE TITLE
`cprop.tools/contains-in?` doesn't work with vectors

### ISSUE THREAD

**Issue by DarinDouglass** [tolitius/cprop#37]
Given the following config:

```clojure
{:zookeeper {:hosts ["localhost:2181"]}}
```

If you attempt to override the `localhost` string with `ZOOKEEPER__HOSTS__0` (by using the `cprop.tools/parse-num-keys` key parse fn), nothing will happen.

This is because `cprop.tools/contains-in?` assumes it is [only working with maps](https://github.com/tolitius/cprop/blob/master/src/cprop/tools.cljc#L85).

**Comment by tolitius** [comment]
the fix is in `[cprop "0.1.17"]`
