### ISSUE TITLE
`load-config :merge` option not merging in specified order

### ISSUE THREAD

**Issue by lucian303** [tolitius/cprop#39]
I'm trying to get my `config.edn` values to override the environment variables but this seems impossible? It doesn't seem to matter what order I specify the arguments to merge.
 
```
(def bad (load-config
           :merge
           [(mount/args)
            (source/from-system-props)
            (source/from-env)
            (source/from-file "config.edn")]))
```

I even tried to merge things myself and it still overrides w/ the environment variables:

```
(def still-bad (load-config
                             :merge
                             [(apply merge [(mount/args)
                                            (source/from-system-props)
                                            (source/from-env)
                                            (source/from-file "config.edn")])]))

```

Or specified the file:
```
(def nope (load-config
                             :file "config.edn"
                             :merge
                             [(mount/args)
                              (source/from-system-props)
                              (source/from-env)]))
```

Is this a bug as it obviously seems to be or just an impossibility with the current system? The docs says it's composable, but clearly, that does not refer to respecting the order property sources or not overwriting them w/ env variables. Why even have a :merge option if it doesn't do anything different than calling `(load-config)` with no args?

**Comment by tolitius** [comment]
does the [docs](https://github.com/tolitius/cprop#override-all-configs) help?

**Comment by lucian303** [comment]
Yes, thank you. `:override-with` seems to be what I was looking for:
```
(def good (load-config
                             :merge
                             [(mount/args)
                              (source/from-system-props)
                              (source/from-env)]
                             :override-with
                             (source/from-file "config.edn")))
```
