### ISSUE TITLE
Add deps.edn - for git consumption ?

### ISSUE THREAD

**Issue by ieugen** [tolitius/cprop#58]
Hi,

Would you be open to adding a deps.edn for this library so that it can be consumed from git ?
I found that deps.edn makes it easy to experiment / use other branches.

**Comment by tolitius** [comment]
yep, good idea. [added](https://github.com/tolitius/cprop/commit/d697373d847b70f3cdd2f4ffbd96cd382a12b793)

[[cprop "0.1.20"](https://clojars.org/cprop/versions/0.1.20)] is built w/ "`deps.edn`"

let me know if it works for you

**Comment by ieugen** [comment]
Works nicely.
Thanks.
