### ISSUE TITLE
Support For Boolean Types?

### ISSUE THREAD

**Issue by xcthulhu** [tolitius/cprop#6]
Hi!

I am using cprop for a project and I was wondering if it could have support for coercing ENV/System Property values to boolean types.

For example:

``` DEBUG=true lein test ```

Should set `DEBUG` to `true` (right now it sets it to "true")

**Comment by tolitius** [comment]
sure, try `cprop-0.1.7-SNAPSHOT`

let me know if it works for you

**Comment by tolitius** [comment]
feel free to open if you have more questions

**Comment by xcthulhu** [comment]
I'm so sorry for getting back to you painfully late here.

I can confirm that 1.7.0-SNAPSHOT works like a champ.

Thanks for doing this; I had basically invented CPROP independently for myself before I saw this on reddit. Same priority for System properties and environment variables and everything... although not nearly as slick.

Keep up the good work dude, you're the man :D

**Comment by tolitius** [comment]
thanks:) I just released `[cprop "0.1.7"]` so you don't have to carry the snapshot around.
