### ISSUE TITLE
Substitution with falsey values

### ISSUE THREAD

**Issue by solicode** [tolitius/cprop#7]
Let's say I have a `config.edn` like so:

```clojure
{:a "a"
 :b true
 :c false
 :d nil}
```

And I'm doing a plain `(load-config)` with no special options set.

By setting environment variables, I can only substitute `:a` and `:b`. Both `:c` and `:d` are ignored, and I can't seem to substitute them through environment variables no matter what I do. I'm assuming this is happening because both `:c` and `:d` are falsey, but this is not intended behavior is it? I can't imagine that it is, but I just wanted to check.

**Comment by tolitius** [comment]
good catch. try `cprop-0.1.7-SNAPSHOT`. let me know if it works for you.

you could still substitute with ENV / sysprops [using them as sources](https://github.com/tolitius/cprop#merging-with-all-system-and-env) but I agree, if the key is there, no matter what the value is it should obey the default substitution.

**Comment by solicode** [comment]
That fixed the issue I was having. Thanks for the quick response. :)

**Comment by tolitius** [comment]
sure, welcome. I'll close this. feel free to open if there are more questions
